package dev.platovco.mentorium.core.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class AppColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val surface: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val onSurface: Color,
    val containerLowest: Color,
    val containerLow: Color,
    val container: Color,
    val containerHigh: Color,
    val containerHighest: Color,
    val surfaceBright: Color,
    val surfaceDim: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val accent: Color,
    val background: Color,
    val onBackground: Color,
    val backgroundVariant: Color,
    val onBackgroundVariant: Color,
) {
    companion object {
        val LightColors = AppColors(
            primary = Color(0xFF455E91),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFD8E2FF),
            onPrimaryContainer = Color(0xFF001A42),
            secondary = Color(0xFF575E71),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFDBE2F9),
            onSecondaryContainer = Color(0xFF141B2C),
            tertiary = Color(0xFF715573),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFCD7FB),
            onTertiaryContainer = Color(0xFF29132D),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            surface = Color(0xFFF9F9FF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF3F3FA),
            surfaceContainer = Color(0xFFEEEDF4),
            surfaceContainerHigh = Color(0xFFE8E7EF),
            surfaceContainerHighest = Color(0xFFE2E2E9),
            onSurface = Color(0xFF1A1B20),
            containerLowest = Color(0xFFFFFFFF),
            containerLow = Color(0xFFF3F3FA),
            container = Color(0xFFEEEDF4),
            containerHigh = Color(0xFFE8E7EF),
            containerHighest = Color(0xFFE2E2E9),
            surfaceBright = Color(0xFFF9F9FF),
            surfaceDim = Color(0xFFDAD9E0),
            surfaceVariant = Color(0xFFE1E2EC),
            onSurfaceVariant = Color(0xFF44474F),
            outline = Color(0xFF75777F),
            outlineVariant = Color(0xFFC5C6D0),
            accent = Color(0xFF25B688),
            background = Color(0xFFEEEDF4),
            onBackground = Color(0xFF455E91),
            backgroundVariant = Color(0xFF455E91),
            onBackgroundVariant = Color(0xFFF9F9FF),
        )

        val DarkColors = AppColors(
            primary = Color(0xFFAEC6FF),
            onPrimary = Color(0xFF112F60),
            primaryContainer = Color(0xFF2C4678),
            onPrimaryContainer = Color(0xFFD8E2FF),
            secondary = Color(0xFFBFC6DC),
            onSecondary = Color(0xFF293041),
            secondaryContainer = Color(0xFF3F4759),
            onSecondaryContainer = Color(0xFFDBE2F9),
            tertiary = Color(0xFFDFBCDF),
            onTertiary = Color(0xFF293041),
            tertiaryContainer = Color(0xFF583E5A),
            onTertiaryContainer = Color(0xFFFCD7FB),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            surface = Color(0xFF111318),
            surfaceContainerLowest = Color(0xFF0C0E13),
            surfaceContainerLow = Color(0xFF1A1B20),
            surfaceContainer = Color(0xFF1E1F25),
            surfaceContainerHigh = Color(0xFF282A2F),
            surfaceContainerHighest = Color(0xFF33353A),
            onSurface = Color(0xFFE2E2E9),
            containerLowest = Color(0xFF0C0E13),
            containerLow = Color(0xFF1A1B20),
            container = Color(0xFF1E1F25),
            containerHigh = Color(0xFF282A2F),
            containerHighest = Color(0xFF33353A),
            surfaceBright = Color(0xFF37393E),
            surfaceDim = Color(0xFF111318),
            surfaceVariant = Color(0xFF44474F),
            onSurfaceVariant = Color(0xFFC5C6D0),
            outline = Color(0xFF8E9099),
            outlineVariant = Color(0xFF44474F),
            accent = Color(0xFF1DFFB7),
            background = Color(0xFF1A1B20),
            onBackground = Color(0xFFE2E2E9),
            backgroundVariant = Color(0xFF455E91),
            onBackgroundVariant = Color(0xFFF9F9FF),
        )
    }
}

internal val LocalAppColors = staticCompositionLocalOf {
    AppColors.LightColors
}